name: Generate Snake

on:
  # Jalankan otomatis setiap 12 jam
  schedule:
    - cron: "0 */12 * * *" 
  
  # Jalankan manual jika tombol ditekan
  workflow_dispatch:
  
  # Jalankan setiap kali push ke branch master/main
  push:
    branches:
    - master
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          # Nama user GitHub Anda
          github_user_name: Myunikon
          # Output file svg (ular biasa & dark mode)
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to GitHub
        uses: crazy-max/gh-action-github-pages@v2.1.3
        with:
          # Branch target (jangan diganti, ini akan membuat branch 'output' otomatis)
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
